--[[
	ArtData.lua  (generated by tools/upload_art.py; do not edit by hand)
	Uploaded game art: key (path under art/ without .png) -> Roblox image id.
	ArtData.Image(key) gives "rbxassetid://<id>" or nil when that picture is not uploaded,
	so callers keep their drawn fallback.
]]

local ArtData = {}

ArtData.Ids = {
	["portraits/Knight"] = 108323809289389,
} :: { [string]: number }

function ArtData.Image(key: string?): string?
	local id = key and ArtData.Ids[key]
	return id and ("rbxassetid://" .. tostring(id)) or nil
end

return ArtData
