"""Generate src/shared/MeshCatalog.lua from meshes/catalog.json + meshes/uploaded_ids.json.

    python3 tools/gen_mesh_catalog.py

Run after `python3 blender/build.py` and after uploading (tools/upload_meshes.py does it
automatically). Models without an uploaded id get AssetId = 0 and the game keeps using
its built-in part models for them.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAT = os.path.join(ROOT, "meshes", "catalog.json")
IDS = os.path.join(ROOT, "meshes", "uploaded_ids.json")
OUT = os.path.join(ROOT, "src", "shared", "MeshCatalog.lua")


def num(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def vec(v):
    return "{" + ", ".join(num(x) for x in v) + "}"


def color(c):
    return "Color3.fromRGB(%d, %d, %d)" % tuple(round(x * 255) for x in c)


def main():
    with open(CAT) as f:
        catalog = json.load(f)
    ids = {}
    if os.path.exists(IDS):
        with open(IDS) as f:
            ids = json.load(f)
    lines = [
        "--[[",
        "\tMeshCatalog.lua - GENERATED by tools/gen_mesh_catalog.py. Do not edit by hand.",
        "\tEvery Blender-built mesh model (blender/models/*.py): its uploaded asset id and",
        "\tits pieces. Offsets are piece centres in studs from the model origin (ground",
        "\tcentre for standing models, centre for projectiles), Roblox axes. Pivot is the",
        "\tjoint an animated piece swings around, relative to the piece centre.",
        "\tAssetId = 0 means not uploaded yet: the game falls back to part-built models.",
        "\tBounds = { min, max } of the whole model (studs, Roblox axes, from the origin).",
        "\tTransparency / Shadow are per piece; Joints (heroes) are the rig joint points.",
        "]]",
        "",
        "local MeshCatalog = {}",
        "",
        "MeshCatalog.Models = {",
    ]
    for m in catalog:
        lines.append(f"\t{m['name']} = {{")
        lines.append(f"\t\tAssetId = {int(ids.get(m['name'], 0))},")
        lines.append(f"\t\tCategory = \"{m['category']}\",")
        if m.get("bounds"):
            lines.append(f"\t\tBounds = {{ {vec(m['bounds'][0])}, {vec(m['bounds'][1])} }},")
        if m.get("joints"):
            lines.append("\t\tJoints = { " + ", ".join(f"{k} = {vec(v)}" for k, v in sorted(m["joints"].items())) + " },")
        pal = m.get("preview_palette", {})
        if pal:
            lines.append("\t\tPalette = { " + ", ".join(f"{k} = {color(v)}" for k, v in sorted(pal.items())) + " },")
        lines.append("\t\tPieces = {")
        for p in m["pieces"]:
            parts = [f"Name = \"{p['name']}\"", f"Slot = \"{p['slot']}\"", f"Material = \"{p['material']}\"",
                     f"Offset = {vec(p['offset'])}", f"Size = {vec(p['size'])}"]
            if p.get("anim"):
                parts.append(f"Anim = \"{p['anim']}\"")
                parts.append(f"Pivot = {vec(p['pivot'])}")
            if p.get("bone"):
                parts.append(f"Bone = \"{p['bone']}\"")
            if p.get("transparency"):
                parts.append(f"Transparency = {num(p['transparency'])}")
            if p.get("shadow"):
                parts.append("Shadow = true")
            lines.append("\t\t\t{ " + ", ".join(parts) + " },")
        lines.append("\t\t},")
        lines.append("\t},")
    lines += ["}", "", "return MeshCatalog", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(catalog)} models, {sum(1 for m in catalog if ids.get(m['name']))} uploaded")


if __name__ == "__main__":
    main()
