"""Generate src/shared/Palette.lua from art/palette.json (the single colour source).

    python3 tools/gen_palette.py

Blender reads art/palette.json directly (blender/style.py); the game reads Palette.lua.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "art", "palette.json")
OUT = os.path.join(ROOT, "src", "shared", "Palette.lua")


def main():
    with open(SRC) as f:
        data = json.load(f)
    lines = [
        "--[[",
        "\tPalette.lua - GENERATED by tools/gen_palette.py from art/palette.json. Do not edit.",
        "\tThe SWARM colour palette, shared with the Blender models. Use these through",
        "\tTheme (src/shared/Theme.lua) rather than hard-coding RGB values.",
        "]]",
        "",
        "local Palette = {",
    ]
    for key, value in data.items():
        if key.startswith("_"):
            continue
        h = value.lstrip("#")
        r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
        lines.append(f"\t{key} = Color3.fromRGB({r}, {g}, {b}),")
    lines += ["}", "", "return Palette", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {sum(1 for k in data if not k.startswith('_'))} colours")


if __name__ == "__main__":
    main()
