"""Upload the game art under art/ (everything except art/icons/*.png, which upload_icons.py
handles, and art/store, which goes on the Roblox store page by hand) as Image assets, then
write src/shared/ArtData.lua.

    ROBLOX_USER_ID=20194281 python3 tools/upload_art.py [--only portraits/Knight,...] [--force]
    python3 tools/upload_art.py --gen-only      # just rewrite ArtData.lua from the JSON

* Auth and upload work like tools/upload_icons.py (the cloud environment adds the API key
  for apis.roblox.com; elsewhere set ROBLOX_API_KEY).
* Keys are the path under art/ without ".png", e.g. "portraits/Knight", "icons/ui/sym_gear".
* Each picture is uploaded at most MAX_SIDE pixels on its long side (aspect kept).
* Results: art/uploaded_art.json {key: imageId}. Already uploaded keys are skipped unless
  --force. Nothing is written for a failed upload (never a guessed id).
"""

import argparse
import json
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import upload_icons as up  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "art")
IDS = os.path.join(ART, "uploaded_art.json")
LUA = os.path.join(ROOT, "src", "shared", "ArtData.lua")
TMP = os.path.join(ROOT, "art", ".upload_tmp")
SKIP_TOP = {"store"}
MAX_SIDE = {"screens": 1024, "arenas": 1024}


def keys():
    out = []
    for dirpath, _, files in os.walk(ART):
        rel = os.path.relpath(dirpath, ART)
        if rel == "." or rel.split(os.sep)[0] in SKIP_TOP or rel.startswith(".upload_tmp"):
            continue
        if rel == "icons":  # the 75 item icons: tools/upload_icons.py
            continue
        for fn in files:
            if fn.endswith(".png"):
                out.append((rel.replace(os.sep, "/") + "/" + fn[:-4], os.path.join(dirpath, fn)))
    return sorted(out)


def shrink(src, key):
    os.makedirs(TMP, exist_ok=True)
    top = key.split("/")[0]
    side = MAX_SIDE.get(top, 512)
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    if max(w, h) > side:
        s = side / max(w, h)
        img = img.resize((round(w * s), round(h * s)), Image.LANCZOS)
    dst = os.path.join(TMP, key.replace("/", "__") + ".png")
    img.save(dst, optimize=True)
    return dst


def gen(ids):
    lines = [
        "--[[",
        "\tArtData.lua  (generated by tools/upload_art.py; do not edit by hand)",
        "\tUploaded game art: key (path under art/ without .png) -> Roblox image id.",
        "\tArtData.Image(key) gives \"rbxassetid://<id>\" or nil when that picture is not uploaded,",
        "\tso callers keep their drawn fallback.",
        "]]",
        "",
        "local ArtData = {}",
        "",
        "ArtData.Ids = {",
    ]
    for k in sorted(ids):
        lines.append('\t["%s"] = %d,' % (k, ids[k]))
    lines += [
        "} :: { [string]: number }",
        "",
        "function ArtData.Image(key: string?): string?",
        "\tlocal id = key and ArtData.Ids[key]",
        "\treturn id and (\"rbxassetid://\" .. tostring(id)) or nil",
        "end",
        "",
        "return ArtData",
        "",
    ]
    with open(LUA, "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--gen-only", action="store_true")
    args = ap.parse_args()
    ids = up.load(IDS)
    if not args.gen_only:
        key = os.environ.get("ROBLOX_API_KEY")
        user_id = os.environ.get("ROBLOX_USER_ID")
        if not user_id:
            sys.exit("Set ROBLOX_USER_ID first.")
        only = {x for x in args.only.split(",") if x}
        failed = []
        for k, path in keys():
            if only and k not in only:
                continue
            if ids.get(k) and not args.force:
                continue
            try:
                name = k.replace("/", "_")
                ids[k] = up.upload(shrink(path, k), name, key, user_id)
                up.save(IDS, ids)
                print(f"{k:<40} -> {ids[k]}")
            except Exception as err:
                failed.append(k)
                print(f"{k:<40} FAILED: {err}")
        if failed:
            print("Failed: " + ", ".join(failed))
    gen(ids)
    print(f"ArtData.lua: {len(ids)} pictures")


if __name__ == "__main__":
    main()
